/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export default {
    "aws_project_region": "sa-east-1"
};


// export module.exports = {default: awsmobile};
